source 'https://rubygems.org'

gem 'rails', '4.0.2'
gem 'annotate'
gem 'sqlite3'

gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

group :doc do
  gem 'sdoc', require: false
end

group :development, :test do
  gem 'rspec-rails'
  gem 'jasmine', github: 'pivotal/jasmine-gem', ref: 'e810540'
  gem 'jasmine-core', '1.3.1'
  gem 'jasmine-headless-webkit'
  gem 'factory_girl_rails'
  gem 'poltergeist'
  gem 'capybara'
  gem 'launchy'
  gem 'faker'
  gem 'database_cleaner'
end

gem 'backbone-on-rails'
